-- Baseline: saved_recipes was first created in the Supabase dashboard.
-- This file records that schema so the repository can rebuild it.
-- It is idempotent and does not change the existing production table.
begin;

create table if not exists public.saved_recipes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  meal_id text not null,
  meal_name text not null,
  meal_image text,
  created_at timestamptz not null default now(),
  constraint saved_recipes_user_id_meal_id_key unique (user_id, meal_id)
);

alter table public.saved_recipes enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'saved_recipes' and policyname = 'Users can view their own saved recipes') then
    create policy "Users can view their own saved recipes"
      on public.saved_recipes for select to authenticated
      using (auth.uid() = user_id);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'saved_recipes' and policyname = 'Users can save their own recipes') then
    create policy "Users can save their own recipes"
      on public.saved_recipes for insert to authenticated
      with check (auth.uid() = user_id);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'saved_recipes' and policyname = 'Users can delete their own saved recipes') then
    create policy "Users can delete their own saved recipes"
      on public.saved_recipes for delete to authenticated
      using (auth.uid() = user_id);
  end if;
end
$$;

commit;
